name: Build and deploy containers

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
      build-images:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build images'
            run: |
              docker build suse_leap_arc --tag ghcr.io/aardsoft/leap_arc:latest
              docker push ghcr.io/aardsoft/leap_arc:latest
