name: Build and deploy kiwi containers

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-images:
    runs-on: opensuse-leap16-imgbuild
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build leap base image
        uses: aardsoft/ci-actions/kiwi-build-multiarch@master
        with:
          image-directory: leap16-base
          extra-architectures: aarch64
          repository: https://download.opensuse.org/distribution/leap/16.0/repo/oss

      - name: Build leap base image
        uses: aardsoft/ci-actions/kiwi-build-multiarch@master
        with:
          image-directory: leap-base
          extra-architectures: aarch64
