name: Build and deploy kiwi containers

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-images:
    runs-on: opensuse-leap-imgbuild
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build leap base image
        uses: aardsoft/ci-actions/kiwi-build-multiarch@master
        with:
          image-directory: leap-base
          extra-architectures: aarch64
          extra-repositories: https://download.opensuse.org/update/leap/15.6/oss/
